# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
- main
- fb/*

pool:
  vmImage: ubuntu-latest

variables:
  DOCKER_REPO: ziaurrehmans/hello-fe
steps:

- task: Npm@1
  displayName: Install NPM Dependencies
  inputs:
    command: 'install'
    workingDir: '.'

- task: Npm@1
  displayName: Make Build
  inputs:
    command: 'custom'
    workingDir: '.'
    customCommand: 'build --prod'

- task: Docker@2
  displayName: Build Docker Image and Push
  inputs:
    containerRegistry: 'Dockerhub-ServiceConnection'
    repository: $(DOCKER_REPO)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest


- script: |
    docker run -p 80:80 $(DOCKER_REPO):latest
    sleep 5
    curl localhost
  displayName: 'Sanity Check'