# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
# - main

pool:
  vmImage: ubuntu-latest

steps:
# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#     npm install
#   displayName: 'Run a multi-line script'
- task: Npm@1
  displayName: Install NPM Dependencies
  inputs:
    command: 'install'
    workingDir: 'package.json'

- task: Npm@1
  displayName: Make Build
  inputs:
    command: 'custom'
    workingDir: 'package.json'
    customCommand: 'build --prod'

- task: Docker@2
  displayName: Build Docker Image and Push
  inputs:
    containerRegistry: 'Dockerhub-ServiceConnection'
    repository: 'hello-fe'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest


